# Generated by Django 4.1.7 on 2023-02-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, choices=[('sofas', 'Sofa'), ('chairs', 'Chairs'), ('tables', 'Tables'), ('storage', 'Storage'), ('beds', 'Beds'), ('mattresses', 'Mattresses'), ('dressers', 'Dressers'), ('dressers', 'Dressers'), ('nightstands', 'Nightstands'), ('desks', 'Desks')], max_length=60, null=True),
        ),
    ]
